Task 1:

1.Write a function to compute 5/0 and use try/except to catch the exceptions.


In [11]:
class ZeroExcept:
    def div_by_zero(self):
         return 5/0


        
z=ZeroExcept()
try:
    z.div_by_zero()
except Exception as e:
    print("ERR:Divide by zero exception caught:"+str(e))

ERR:Divide by zero exception caught:division by zero


2.Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket

In [12]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print(str(sub)+" "+str(verb)+" "+str(obj))

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Task 2:

1.Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [1]:
import numpy as np

In [2]:
inlist=[10,20,30,40]
v=np.array(inlist)
res=np.vander(v)

print(res)

[[ 1000   100    10     1]
 [ 8000   400    20     1]
 [27000   900    30     1]
 [64000  1600    40     1]]
